### PR TITLE
2022-02-01-ner_deid_subentity_fr

### PR DESCRIPTION
**Pull request by jsl-models**

### CODE REVIEW

**Comment by luca-martial** [comment]
hey @josejuanmartinez @vkocaman i'm uploading new word embeddings, so the sample code for this model contains what I think will be the name of the word embeddings, but it's not 100% sure yet: 
```
embeddings = WordEmbeddingsModel.pretrained("word2vec_wac_200", "fr")\
	.setInputCols(["sentence", "token"])\
	.setOutputCol("word_embeddings")
```

**Comment by luca-martial** [comment]
These were the [old embeddings](https://github.com/JohnSnowLabs/spark-nlp/pull/6825) - not good. These are the [new embeddings](https://github.com/JohnSnowLabs/spark-nlp/pull/6843) - much better.

**Review by josejuanmartinez — CHANGES_REQUESTED** [review]
Hi! Good job. In scala code, you are missing the Array() constructor where an array is expected. To see when it is, check brackets in Python code.

Also, although I did not that in the Spanish one, I think using a multilingual sentence detector ('xx') makes more sense.

**Comment by luca-martial** [comment]
@josejuanmartinez fixed!

**Comment by luca-martial** [comment]
uploading new, better performing version

**Pull request closed without merging**
