### PR TITLE
2022-01-18-distilbert_base_token_classifier_masakhaner_xx

### PR DESCRIPTION
**Pull request by jsl-models**

### CODE REVIEW

**Comment by murat-gunay** [comment]
> @murat-gunay Hi! Has the text been taken from the test dataset or a trusted source (meaning no Machine Translation)?

@josejuanmartinez 

I have found a yoruba text from internet then I have modified the sentence a little bit using translator. I wasted more than an hour 😄 to find good text. Didn't you like it? do you want me to change?

**Comment by josejuanmartinez** [comment]
> > @murat-gunay Hi! Has the text been taken from the test dataset or a trusted source (meaning no Machine Translation)?
> 
> @josejuanmartinez
> 
> I have found an original yoruba text from internet then I have modified the sentence a little bit using translator. I wasted more than an hour 😄 to find good text. Didn't you like it? do you want me to change?

I like it, my concern is that I think it's not correct. Can't we just have a sentence from the dataset?

**Comment by murat-gunay** [comment]
> > > @murat-gunay Hi! Has the text been taken from the test dataset or a trusted source (meaning no Machine Translation)?
> > 
> > 
> > @josejuanmartinez
> > I have found an original yoruba text from internet then I have modified the sentence a little bit using translator. I wasted more than an hour 😄 to find good text. Didn't you like it? do you want me to change?
> 
> I like it, my concern is that I think it's not correct. Can't we just have a sentence from the dataset?

image
@josejuanmartinez  I took a text from training data

**Review by josejuanmartinez — APPROVED** [review]
Thank you, looks good!

**Pull request merged**
