### PR TITLE
Added Code for pushing to hub

### PR DESCRIPTION
**Pull request by ahmedlone127**
Added Push to Hub for Models and Pipelines 

### Parameters

| Name  | Type|
| ------------- |:-------------:|
|Name	|Type|
|name (required)|	string|
|task (required)|	string|
|sparkVersion (required)|	string|
|sparknlpVersion (required)|	string|
|language (required)|	string|
|license	|string ["Open Source", "Licensed"]|
|tags|	array of strings|
|supported|	boolean|
|title (required)|	string|
|dependencies|	string|
|description (required)|	string|
|predictedEntities|	string|
|howToUse|	string|
|liveDemo|	string|
|runInColab|	string|
|pythonCode (required)|	string|
|scalaCode|	string|
|nluCode|	string||
|results|	string|
|dataSource|	string|
|includedModels	|string|
|benchmarking|	string|

### Example Usage 

```
from python.sparknlp.upload_to_hub import PushToHub
sample_upload = {
    "name":"analyze_sentiment_ml",
    "task":'Sentiment Analysis',
    'title':'Analyze Sentiment Machine Learning ',
    'sparkVersion':"3.0",
    'sparknlpVersion':'Spark NLP 4.0.0',
    'language':'en',
    'license':'Open Source',
    'description':'''The analyze_sentiment_ml is a pretrained pipeline that we can use to process text with a simple pipeline that performs basic processing steps and predicts sentiment  .
         It performs most of the common text processing tasks on your dataframe''',
    'pythonCode':'''from sparknlp.pretrained import PretrainedPipeline
pipeline = PretrainedPipeline("analyze_sentiment_ml", "en")

result = pipeline.annotate("""I love johnsnowlabs!  """)''',
'model_zip_path':'pos_ud_bokmaal_nb_3.4.0_3.0_1641902661339.zip'

}

PushToHub.upload_to_modelshub_and_fill_form_API(sample_upload,GitToken )

```

### CODE REVIEW

**Comment by ahmedlone127** [comment]
If someone calls `push_to_hub` directly with a simple dict like that , we can for sure add the other required fields and keep some of the ones that we can't generate empty but,I think we should also make `task` and `pythonCode` required, we can generate `Title` and `Description` but without those two the model won't make a lot of sense (useable)

**Comment by ahmedlone127** [comment]
Hey, @maziyarpanahi  do we still support spark version 2? I am asking because for the `sparknlpVersion`  we can simply import the library and do `sparknlp.version()`  but for `sparkVersion` we would have to start a spark session and we could avoid that if we keep it at 3 by default ?

**Comment by maziyarpanahi** [comment]
Hi,

No, by default and until further notice the spark version is 3.0 for models/pipelines. 
For spark nlp version, if it's empty we can take it from the current or else users can specify something else I guess

**Comment by ahmedlone127** [comment]
that sounds good, I have also added the zip function we talked about to zip folders, I was thinking about what was a good way to add the last part
image
I think  we should check for this file in the metadata folder in the given input and if it exists we assume it's apache spark .

**Comment by maziyarpanahi** [comment]
> that sounds good, I have also added the zip function we talked about to zip folders, I was thinking about what was a good way to add the last part image I think we should check for this file in the metadata folder in the given input and if it exists we assume it's apache spark .

I will loop in @pabla who has more insight. @pabla So we basically want to have a first simple check to avoid Models Hub returning an error when it comes to the format of the saved model in Spark/Spark NLP.

**Comment by ahmedlone127** [comment]
Hey @maziyarpanahi  I made the changes we discussed , please review them and let me know if they look good :)

**Comment by maziyarpanahi** [comment]
> Hey @maziyarpanahi I made the changes we discussed , please review them and let me know if they look good :)

Thanks for this, I have pushed some changes. Can we have a small unit test for this? Obviously, you can tag it as a `slow` but we can simply load a NerDLModel.pretrained(), save it and use a sample code to upload it to see if it works. (you can leave GIT_TOKEN empty and we manually add it when we do manual tests)

**Comment by ahmedlone127** [comment]
Hey @maziyarpanahi  I made a  test

```
import unittest
import sparknlp
from sparknlp.annotator import *
from sparknlp.common import *
from sparknlp.base import *
from pyspark.ml import Pipeline
from upload_models_to_hub import PushToHub



class TestStringMethods(unittest.TestCase):

    def load_and_upload():
        """Loads and uploads a Spark NLP Model 
        """
        spark = sparknlp.start()
        ner_model = NerDLModel.pretrained("ner_aspect_based_sentiment")\
        .setInputCols(["document", "token", "embeddings"])\
        .setOutputCol("ner")
        nlp_pipeline = Pipeline(stages=[ ner_model])
        model = nlp_pipeline.fit(spark.createDataFrame([[""]]).toDF("text"))
        model.write().overwrite().save(f"test")
        PushToHub.push_to_hub('test_model_hub_upload',
                    'en',
                    'test',
                    'Summarization',
                    'restaurant_pipeline = PretrainedPipeline("nerdl_restaurant_100d_pipeline", lang = "en")',
                    GIT_TOKEN = '')


if __name__ == '__main__':
    unittest.main()
```

**Review by maziyarpanahi — APPROVED** [review]

**Pull request merged**
