### PR TITLE
Enabling MFA support for S3 features and downlad graph files from S3 for NERDL

### PR DESCRIPTION
**Pull request by danilojsl**
## Description

This change enables MFA support for all S3 integration that sparknlp has available. In addition, adds option for download NERDL graphs from S3.

## Motivation and Context

Some AWS accounts have MFA configuration which will not allow using S3 integration with sparknlp.
By redesigning AWS S3 client integration, now users with MFA configuration can use all S3 features available in sparknlp 

## How Has This Been Tested?

Adding unit tests and E2E tests with Google Colab and Databricks (scala) notebooks 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Code improvements with no or little impact
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [CONTRIBUTING](http://nlp.johnsnowlabs.com/contribute.html) page.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by maziyarpanahi** [comment]
Hi @danilojsl 

Why do we need the param `s3BucketName` in NerDLApproach? Can't we get the S3 bucket from the `graphFolder` param? 

- http://s3.amazonaws.com/[bucket_name]/
- http://[bucket_name].s3.amazonaws.com/

**Comment by danilojsl** [comment]
> Hi @danilojsl
> 
> Why do we need the param `s3BucketName` in NerDLApproach? Can't we get the S3 bucket from the `graphFolder` param?
> 
> * [http://s3.amazonaws.com/[bucket_name]/](http://s3.amazonaws.com/%5Bbucket_name%5D/)
> * http://[bucket_name].s3.amazonaws.com/
> 
> Could you also leave an example for MFA, how it should be set before/after SparkSession to be included in all S3 related operations in Spark NLP?

Done. Now it uses `graphFolder` param with the following format
_s3://myBucketName/my/path/location/_

**Comment by maziyarpanahi** [comment]
Thanks @danilojsl 
So you can remove `s3BucketName` with setter/getter from Scala and Python?

**Comment by danilojsl** [comment]
The last commits removed `s3BucketName` parameter which is no longer used. I didn't notice there kept in the last merge. Thanks @maziyarpanahi

**Review by maziyarpanahi — APPROVED** [review]

**Comment by maziyarpanahi** [comment]
> The last commits removed `s3BucketName` parameter which is no longer used. I didn't notice it kept in the last merge. Thanks @maziyarpanahi

Thanks @danilojsl, LGTM. We can do more tests in 322 branch.

**Pull request merged**
