### PR TITLE
Serialization context spell

### PR DESCRIPTION
**Pull request by albertoandreottiATgmail**
This fix is for solving an issue appearing during training of ContextSpellChecker.
Please hold the merge until we test this.
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Code improvements with no or little impact
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [CONTRIBUTING](http://nlp.johnsnowlabs.com/contribute.html) page.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by maziyarpanahi** [comment]
[ContextSpellChecker wasn't working in Databricks (I think training it)](https://trello.com/c/nTxxPM4x/510-contextspellchecker-wasnt-working-in-databricks-i-think-training-it)

**Comment by xusliebana** [comment]
@maziyarpanahi I cannot see the link to trello. Do you want to test in on databrics?

**Comment by maziyarpanahi** [comment]
Hi @xusliebana 

I asked @danilojsl to test it, but it would be great if you can test it too. This way we are sure since each of you faced this issue differently

**Comment by xusliebana** [comment]
I tested also and was working

**Review by maziyarpanahi — APPROVED** [review]

**Pull request merged**
