### PR TITLE
Bump model card Spark NLP HC version to 4.2.1

### PR DESCRIPTION
**Pull request by luca-martial**
## Description

Several models were accidentally uploaded with Spark NLP for Healthcare version listed as 4.1.0. I am bumping those versions up to Spark NLP HC version 4.2.1

## Motivation and Context

Several models were accidentally uploaded with Spark NLP for Healthcare version 4.1.0.

## How Has This Been Tested?

N/A

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Code improvements with no or little impact
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [CONTRIBUTING](http://nlp.johnsnowlabs.com/contribute.html) page.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by luca-martial** [comment]
I added another version bump to cover 4.2.0 per an internal request

**Comment by maziyarpanahi** [comment]
Hi @luca-martial 

Since the model was uploaded for 4.1.0, the name of the model and the info in metadata.json will be still 4.1.0.

If this model is not 100% compatible with 4.1.0, @pabla will also rename it on S3 and fix the metadata.json. (If there are more than 1 model like this, you can add them all to this PR for Pavel to fix all at once)

**Comment by luca-martial** [comment]
Thanks @maziyarpanahi yes I discussed this with @pabla - the goal was to modify the `compatible_editions` property in models.json for an immediate request by the A-Lab team. Is it ok to proceed without renaming on S3 and metadata.json? There will be another PR in a couple weeks to fix ~30 models, renaming them in S3 and metadata.json. Tagging @Damla-Gurbaz as her team will be in charge of that change

**Comment by luca-martial** [comment]
Hi @maziyarpanahi we will only be modifying 4 models:
- https://github.com/JohnSnowLabs/spark-nlp/blob/cvx-version-bump/docs/_posts/Ahmetemintek/2022-10-12-cvx_code_mapper_en.md
- https://github.com/JohnSnowLabs/spark-nlp/blob/cvx-version-bump/docs/_posts/Ahmetemintek/2022-10-12-cvx_name_mapper_en.md
- https://github.com/JohnSnowLabs/spark-nlp/blob/cvx-version-bump/docs/_posts/Ahmetemintek/2022-10-12-cvx_resolver_pipeline_en.md
- https://github.com/JohnSnowLabs/spark-nlp/blob/cvx-version-bump/docs/_posts/Ahmetemintek/2022-10-12-sbiobertresolve_cvx_en.md

@pabla has modified the s3 file names and metadata.json so this PR should be good to go! We tested this and no issues came up.

**Pull request merged**
