### PR TITLE
Adding Control for Annotators with One Column

### PR DESCRIPTION
**Pull request by danilojsl**
## Description

Adds inputAnnotatorTypes in Python to identify annotators that expect only one column. This allows handling more than one-column inputs in annotators that only process one column by taking only the first one and ignoring the other columns.

## Motivation and Context

Check issue #12981 

## Screenshots (if appropriate):
- Local Unit Tests
- Google Colab

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Code improvements with no or little impact
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [CONTRIBUTING](http://nlp.johnsnowlabs.com/contribute.html) page.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by dataanalyst4lyfe** [comment]
Wait, if I am understanding you correctly:

> by taking only the first one and ignoring the other columns.

That means if I did something like this:
```
annotator.setInputCols(["col_1", "col_2"])
```

When that is executed, only results for `col_2` will be returned.
^ If that is the case, I think that is a very bad idea. 

*My Proposed Solution*
Throw an exception if the user calls `setInputCols()` <- This is for col*s*. The exception message should tell the user to use the single column version (`setInputCol()`).

*Why?*
I think this implementation would reduce the risk of "silent failures", and makes it explicit what should be done. The user will know that they can only pass in 1 column at-a-time, and they won't risk trying to have to debug and wonder why only 1 column is being processed.

@danilojsl - Let me know what you think.

**Comment by maziyarpanahi** [comment]
> **Understanding the Current Solution** Wait, if I am understanding you correctly:
> 
> > by taking only the first one and ignoring the other columns.
> 
> That means if I did something like this:
> 
> ```
> annotator.setInputCols(["col_1", "col_2"])
> ```
> 
> When that is executed, only results for `col_1` will be returned. ^ If that is the case, I think that is a very bad idea.
> 
> **My Proposed Solution** Throw an exception if the user calls `setInputCols()` <- This is for col**s**. The exception message should tell the user to use the single column version (`setInputCol()`).
> 
> **Why?** I think this implementation would reduce the risk of "silent failures", and makes it explicit what should be done. The user will know that they can only pass in 1 column at-a-time, and they won't risk trying to have to debug and wonder why only 1 column is being processed.
> 
> @danilojsl - Let me know what you think.

Hi @dataanalyst4lyfe 
Yes, your assumption was correct, it will silently skip the other inputCols. We actually discussed this to be in sync with Scala/Java behavior which is a hard exception with an error that says this annotator only accepts 1 inputCol. We were going to implement the exception for the reason you explained perfectly, thanks for reminding me.

**Comment by danilojsl** [comment]
@maziyarpanahi, I made the changes to raise an exception when the number of columns is different than expected. So, now the behavior will be synced with Scala

**Comment by maziyarpanahi** [comment]
> @maziyarpanahi, I made the changes to raise an exception when the number of columns is different than expected. So, now the behavior will be synced with Scala

Thanks @danilojsl the new `raise TypeError` will make it exactly like Scala so we won't have use cases where we are not sure what goes in and out of the pipeline.

**Review by maziyarpanahi — APPROVED** [review]

**Pull request merged**
