### PR TITLE
2022-02-11-ner_deid_subentity_fr

### PR DESCRIPTION
**Pull request by jsl-models**

### CODE REVIEW

**Comment by vkocaman** [comment]
@luca-martial  is this the updated model ? did you retrain ?

**Comment by vkocaman** [comment]
> @vkocaman yes, this is retrained on new data here is a summary of what I've added:
> 
> * used the 90%+ coverage embeddings (dim300)
> * created extra synthetic data from my medical records for train set
> * removed all synthetic data from test set
> * there's no overlap between train/test
> * added WikiNER french dataset, including only shorter sentences with less than 10 Os in them
> * separated LOC into COUNTRY and CITY
> * for WikiNER added annotations for dates
> 
> I checked the model outputs on sample text and it's much more robust imo

looks nice ! good job.. what about the generic version ?

**Comment by luca-martial** [comment]
> looks nice ! good job.. what about the generic version ?

Currently training - it's coming!

**Comment by vkocaman** [comment]
Conflicts spotted in PR

**Comment by josejuanmartinez** [comment]
@vkocaman @luca-martial  Same thing I was reporting: Please close any PR until the Pavel fixes the md naming and adds the PySpark version to the md file

**Comment by muhammetsnts** [comment]
Since spark24 version of this model is merged, I will close this not to overwrite on the md file of the spark30 md file. @luca-martial please re-upload this model tomorrow.

**Pull request closed without merging**
