### PR TITLE
2022-01-04-check_spelling_dl_en

### PR DESCRIPTION
**Pull request by jsl-models**

### CODE REVIEW

**Comment by maziyarpanahi** [comment]
@egenc @josejuanmartinez 

we have these pipelines for spark 2.4 already, the spark 3.0 is missing. These pipelines must be saved/uploaded for spark_version: 3.0 (not just choose 3.0, but actually by using spark 3.0)

**Comment by egenc** [comment]
@maziyarpanahi , that is exactly what I did. Created these pipelines using pyspark==3.1.2

**Comment by maziyarpanahi** [comment]
The metadata says `spark_version: 2.4` and it saved them as 2.4 on S3. It won't download these if a user is on spark3.x, so probably the spark version was manually changed in Models Hub UI.

**Comment by egenc** [comment]
so I created these pipelines using `pyspark==3.1.2` . However, when I upload the model, I picked spark compatibility as 2 otherwise these models will not be compatible  with spark 2..x

**Comment by egenc** [comment]
ok, pushing them again. thanks!

**Comment by egenc** [comment]
https://github.com/JohnSnowLabs/spark-nlp/pull/6709

**Comment by maziyarpanahi** [comment]
Thanks @egenc 
it's the same for the other 2 pipelines I closed.

**Comment by egenc** [comment]
totally got it. Fixing them all

**Pull request closed without merging**
