### PR TITLE
Deprecating models not supported anymore in Spark NLP (Open Source)

### PR DESCRIPTION
**Pull request by gadde5300**
## Description

Deprecating old models from `models hub` because they are no longer supported.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Code improvements with no or little impact
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [CONTRIBUTING](http://nlp.johnsnowlabs.com/contribute.html) page.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by murat-gunay — APPROVED** [review]

**Review by josejuanmartinez — APPROVED** [review]
Looks good, thank you!

**Review by josejuanmartinez — CHANGES_REQUESTED** [review]
@gadde5300 Maziyar mentioned no need to remove `ko` model, it was a confusion. Only `tfhub` ones.

**Review by josejuanmartinez — APPROVED** [review]
Looks good and no `ko` removal. Thank you.

**Comment by maziyarpanahi** [comment]
@gadde5300 @josejuanmartinez 

Maybe we don't have to remove the actual model cards anymore, they just introduced a flag called `deprecation`: https://github.com/JohnSnowLabs/spark-nlp/pull/6590#pullrequestreview-827842056

**Pull request closed without merging**
