### PR TITLE
2022-02-22-bert_sequence_classifier_antisemitism_pipeline_en

### PR DESCRIPTION
**Pull request by jsl-models**

### CODE REVIEW

**Comment by murat-gunay** [comment]
I am not sure if `new` may not be needed in scala script.

**Comment by murat-gunay** [comment]
image

**Comment by josejuanmartinez** [comment]
> I am not sure if `new` may not be needed in scala script.

It's needed, thank you!

**Review by josejuanmartinez — CHANGES_REQUESTED** [review]
I know it's late to change `bert_sequence_classifier_antisemitism_en` but for the pipeline, could we return something not 0 / 1 ? We should not have numerical outputs, always classes. In this case, True or False.

**Comment by murat-gunay** [comment]
> I know it's late to change `bert_sequence_classifier_antisemitism_en` but for the pipeline, could we return something not 0 / 1 ? We should not have numerical outputs, always classes. In this case, True or False.

there is no way other than re-importing the model again from HF, I guess.

**Review by josejuanmartinez — APPROVED** [review]

**Pull request merged**
