### PR TITLE
biobertresolve model descriptions generated automatically

### PR DESCRIPTION
**Pull request by jfernandrezj**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Code improvements with no or little impact
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [CONTRIBUTING](http://nlp.johnsnowlabs.com/contribute.html) page.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by HashamUlHaq — APPROVED** [review]

**Review by diatrambitas — CHANGES_REQUESTED** [review]
The models don't have descriptions, the code sample is very generic. Please add more specific code samples + results returned by the models and also benchmarking info.

**Comment by jfernandrezj** [comment]
> The models don't have descriptions, the code sample is very generic. Please add more specific code samples + results returned by the models and also benchmarking info.

Hi Dia these are the md's generated automatically, let's please agree on a scalable process to update these, thanks.
About the results there are very different examples in all the md's we would also need to agree on those to generate them from form information to make it scalable.

**Comment by diatrambitas** [comment]
> > The models don't have descriptions, the code sample is very generic. Please add more specific code samples + results returned by the models and also benchmarking info.
> 
> Hi Dia these are the md's generated automatically, let's please agree on a scalable process to update these, thanks.
> About the results there are very different examples in all the md's we would also need to agree on those to generate them from form information to make it scalable.

Hi Andres, those details need to be added manually. I don't see any scalable/automatic way of doing this. The details are different from model to model. The author will need to provide this information.

**Comment by diatrambitas** [comment]
@jfernandrezj can you please add more relevant code samples for the resolvers together with the returned results (md table). If you have benchmarking info please add those also. Check this page for a complete example: https://nlp.johnsnowlabs.com/2020/04/15/ner_posology_en.html

**Pull request closed without merging**
