### PR TITLE
TFNerDLGraphBuilder

### PR DESCRIPTION
**Pull request by vankov**
A pipeline component for generating Ner DL graphs.

## Description

TFNerDLGraphBuilder can be used to automatically detect the parameters of a needed NerDL graph and generate the graph within a pipeline. It is available in Python only (it needs TensorFlow) but is dependent on the jar which contains the logic for detecting the optimal parameter values. TFNerDLGraphBuilder is based on TFGraphBuilder from the SparkNLP Healthcare project. It can run using either TF 1.15 and TF 2.x - it automatically detects the available TF version and adjusts to it.

## Motivation and Context
Currently the procedure for generating custom NerDL TF graphs is cumbersome - one need to run NerDLApproach on the target dataset, check the error message (if it fails) and then generate the graph with the given set of parameters.  TFNerDLGraphBuilder solves this problem by automatically detecting the optimal values of the parameters from the data and generating the graph.

## How Has This Been Tested?
The component has been tested using a notebook:

https://github.com/JohnSnowLabs/spark-nlp-training/blob/master/python/notebooks/TFNerDLGraphBuilder.ipynb

Most of the changes are in the python module. The Scala implementation of NerDLApproach has been slightly refactored to expose the functionality for detecting the optimal graph parameter values.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Code improvements with no or little impact
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x ] My code follows the code style of this project.
- [ x] My change requires a change to the documentation.
- [ x] I have updated the documentation accordingly.
- [ x] I have read the [CONTRIBUTING](http://nlp.johnsnowlabs.com/contribute.html) page.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by vankov** [comment]
There is one issue that still needs to be addressed: saving the graphs files on HDFS. At the moment files can be only saved in a local (i.e non-distributed) file system. @maziyarpanahi can you help with this?

**Comment by maziyarpanahi** [comment]
> There is one issue that still needs to be addressed: saving the graphs files on HDFS. At the moment files can be only saved in a local (i.e non-distributed) file system. @maziyarpanahi can you help with this?

I will have a look, I also ask @danilojsl to see how we can do this since most logic, in this case, is in Python and outside of Spark.

**Comment by danilojsl** [comment]
I added the changes required to support HDFS/DBFS/S3 and tested it in Google Colab, Databricks and Google Cloud (Dataproc). I'll create notebooks with examples in spark-nlp-workshop repo

**Review by danilojsl — COMMENTED** [review]
@maziyarpanahi, @vankov I added the changes required to support HDFS/DBFS/S3 and tested it in Google Colab, Databricks and Google Cloud (Dataproc). I'll create notebooks with examples in spark-nlp-workshop repo

**Review by maziyarpanahi — APPROVED** [review]

**Pull request merged**
