### PR TITLE
WIP for Review: Doc examples update

### PR DESCRIPTION
**Pull request by hatrungduc**
## Description

End to end examples have been added to the scala docs, to kick start the development process for users.

#### Transfomers:

- [x] TokenAssembler
- [x] Doc2Chunk
- [x] Chunk2Doc
- [x] Finisher
- [x] EmbeddingsFinisher

#### Annotators:

- [x] Tokenizer
- [x] DocumentNormalizer (Text cleaning)
- [x] Normalizer (Text cleaning)
- [x] Stemmer
- [x] Lemmatizer
- [x] StopWordsCleaner
- [x] RegexMatcher
- [x] TextMatcher (Phrase matching)
- [x] Chunker
- [x] NGramGenerator
- [x] DateMatcher
- [x] MultiDateMatcher
- [x] SentenceDetector
- [ ] POSTagger (Part of speech tagger)
- [ ] ViveknSentimentDetector
- [ ] SentimentDetector (Sentiment analysis)
- [ ] WordEmbeddings
- [ ] BertEmbeddings
- [ ] BertSentenceEmbeddings
- [ ] ElmoEmbeddings
- [ ] AlbertEmbeddings
- [ ] XlnetEmbeddings
- [ ] DistilBertEmbeddings `new annotator`
- [ ] RoBertaEmbeddings `new annotator`
- [ ] XlmRoBertaEmbeddings `new annotator`
- [ ] UniversalSentenceEncoder
- [ ] MarianTransformer 
- [ ] T5Transformer
- [ ] SentenceEmbeddings
- [ ] ChunkEmbeddings
- [ ] ClassifierDL (Multi-class Text Classification)
- [ ] MultiClassifierDL (Multi-label Text Classification)
- [ ] SentimentDL (Multi-class Sentiment Analysis annotator)
- [ ] LanguageDetectorDL (Language Detection and Identiffication)
- [ ] YakeModel (Keywords Extraction)
- [ ] NER CRF (Named Entity Recognition CRF annotator)
- [ ] NER DL (Named Entity Recognition Deep Learning annotator)
- [ ] NER Converter (Converts IOB or IOB2 representation of NER to user-friendly)
- [ ] Norvig SpellChecker
- [ ] Symmetric SpellChecker
- [ ] Context SpellChecker
- [ ] Dependency Parsers
- [ ] Untyped Dependency Parser (Unlabeled grammatical relation)
- [ ] Typed Dependency Parser (Labeled grammatical relation)

#### Main Page:
- [ ] Fix Broken Links
- [ ] Add extended examples
- [ ] Add Missing annotators:
  - [ ] SentenceDetectorDL

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Code improvements with no or little impact
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [CONTRIBUTING](http://nlp.johnsnowlabs.com/contribute.html) page.
- [x] I have added tests to cover my changes. (None needed as there are no code changes)
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by maziyarpanahi** [comment]
@hatrungduc 
Thanks for this PR, it's very useful! 👏 Would it be possible to have the same end-to-end examples inside the [annotators](https://nlp.johnsnowlabs.com/docs/en/annotators) page on the Website in this PR (the current code snippets are not intuitive enough to start with that annotator)?

**Comment by hatrungduc** [comment]
> @hatrungduc
> Thanks for this PR, it's very useful! clap Would it be possible to have the same end-to-end examples inside the [annotators](https://nlp.johnsnowlabs.com/docs/en/annotators) page on the Website in this PR (the current code snippets are not intuitive enough to start with that annotator)?

Hi @maziyarpanahi ,
sure! Do you mean to replace all of them in the future? Or which ones specifically did you have in mind

**Comment by maziyarpanahi** [comment]
> > @hatrungduc
> 
> > Thanks for this PR, it's very useful! clap Would it be possible to have the same end-to-end examples inside the [annotators](https://nlp.johnsnowlabs.com/docs/en/annotators) page on the Website in this PR (the current code snippets are not intuitive enough to start with that annotator)?
> 
> 
> 
> Hi @maziyarpanahi ,
> 
> sure! Do you mean to replace all of them in the future? Or which ones specifically did you have in mind

Hi,
I would make them like the licensed documentation to be expandable and have full examples/output. The feedback we got was that the snippet codes are not really useful, so let's replace them all with a full example and we already have links to source and API if someone wants to explore more.

**Comment by hatrungduc** [comment]
> Hi,
> I would make them like the licensed documentation to be expandable and have full examples/output. The feedback we got was that the snippet codes are not really useful, so let's replace them all with a full example and we already have links to source and API if someone wants to explore more.
Ok, will do once I have updated all the classes with an example 👍
I will include it in the last commit, which will contain updates to the main page and the generated scaladocs itself

**Review by maziyarpanahi — APPROVED** [review]

**Pull request merged**
