### PR TITLE
Pydoc Update

### PR DESCRIPTION
**Pull request by DevinTDHa**
# Still WIP
## Description

This PR continues to create a PyDoc documentation for the Python Spark NLP package in the [numpydoc style](https://numpydoc.readthedocs.io/en/latest/format.html).

The PR also includes some minor fixes for the scala doc and other documentation related sources.

### To-Do:

- [x] sparknlp.base
- [x] sparknlp.training
- [ ] sparknlp.functions
- [ ] sparknlp.annotator
  - [x] AlbertEmbeddings
  - [x] BertEmbeddings
  - [x] BertSentenceEmbeddings
  - [x] BigTextMatcher
  - [x] BigTextMatcherModel
  - [x] ChunkEmbeddings
  - [x] ChunkTokenizer
  - [x] ChunkTokenizerModel
  - [x] Chunker
  - [x] ClassifierDLApproach
  - [x] ClassifierDLModel
  - [ ] ContextSpellCheckerApproach
  - [ ] ContextSpellCheckerModel
  - [ ] DateMatcher
  - [ ] DateMatcherUtils
  - [ ] DependencyParserApproach
  - [ ] DependencyParserModel
  - [ ] DistilBertEmbeddings
  - [ ] DocumentNormalizer
  - [ ] ElmoEmbeddings
  - [ ] LanguageDetectorDL
  - [ ] Lemmatizer
  - [ ] LemmatizerModel
  - [ ] MarianTransformer
  - [ ] MultiClassifierDLApproach
  - [ ] MultiClassifierDLModel
  - [ ] MultiDateMatcher
  - [ ] NGramGenerator
  - [ ] NerApproach
  - [ ] NerConverter
  - [ ] NerCrfApproach
  - [ ] NerCrfModel
  - [ ] NerDLApproach
  - [ ] NerDLModel
  - [ ] NerOverwriter
  - [ ] Normalizer
  - [ ] NormalizerModel
  - [ ] NorvigSweetingApproach
  - [ ] NorvigSweetingModel
  - [ ] PerceptronApproach
  - [ ] PerceptronModel
  - [ ] RecursiveTokenizer
  - [ ] RecursiveTokenizerModel
  - [ ] RegexMatcher
  - [ ] RegexMatcherModel
  - [ ] RegexTokenizer
  - [ ] RoBertaEmbeddings
  - [ ] SentenceDetector
  - [ ] SentenceDetectorDLApproach
  - [ ] SentenceDetectorDLModel
  - [ ] SentenceEmbeddings
  - [ ] SentimentDLApproach
  - [ ] SentimentDLModel
  - [ ] SentimentDetector
  - [ ] SentimentDetectorModel
  - [ ] Stemmer
  - [ ] StopWordsCleaner
  - [ ] SymmetricDeleteApproach
  - [ ] SymmetricDeleteModel
  - [ ] T5Transformer
  - [ ] TextMatcher
  - [ ] TextMatcherModel
  - [ ] Token2Chunk
  - [ ] Tokenizer
  - [ ] TokenizerModel
  - [ ] TypedDependencyParserApproach
  - [ ] TypedDependencyParserModel
  - [ ] UniversalSentenceEncoder
  - [ ] ViveknSentimentApproach
  - [ ] ViveknSentimentModel
  - [ ] WordEmbeddings
  - [ ] WordEmbeddingsModel
  - [ ] WordSegmenterApproach
  - [ ] WordSegmenterModel
  - [ ] XlmRoBertaEmbeddings
  - [ ] XlnetEmbeddings
  - [ ] YakeModel

## Motivation and Context

Improves usability for the python package, especially with showing doc strings for functions in notebooks.

## How Has This Been Tested?

No changes to functionality, Tests have been re run
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Code improvements with no or little impact
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [CONTRIBUTING](http://nlp.johnsnowlabs.com/contribute.html) page.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by maziyarpanahi** [comment]
@DevinTDHa 
Even though the name `_static` directory has changed, but all the references are still to `_static/` like `_static/pygments.css` which is not acceptable by GitHub Pages. 

Is there a way to use a Python script provided by the maintainer to rename those references? (https://github.com/sphinx-doc/sphinx/issues/2202) - we cannot use `. nojekyll` since it must be in the root `docs/` and we have Jekyll template and it won't render it if we use it.

**Comment by DevinTDHa** [comment]
> @DevinTDHa
> Even though the name `_static` directory has changed, but all the references are still to `_static/` like `_static/pygments.css` which is not acceptable by GitHub Pages.
> 
> Is there a way to use a Python script provided by the maintainer to rename those references? ([sphinx-doc/sphinx#2202](https://github.com/sphinx-doc/sphinx/issues/2202)) - we cannot use `. nojekyll` since it must be in the root `docs/` and we have Jekyll template and it won't render it if we use it.

Hi @maziyarpanahi,

Is it not correctly rendering for you? In the Makefile script, there is a command that will rename all references to _static and other underscore folders in the source files to the non underscored version

https://github.com/JohnSnowLabs/spark-nlp/pull/5884/commits/5bace1db7ce43ff8d50edc08c9172c49094c6bde#diff-8b66e9ccea0410f10112a08a1219ffc7682ff23760bb3c09d1162dda0d66a842R4

I tested it locally with a jekyll instance hosting /docs. Used to render wrongly before but now it works as expected.

**Comment by maziyarpanahi** [comment]
@DevinTDHa 
I have a test repo that uses `docs/` folder for full testing with GitHub pages: 
https://maziyarpanahi.github.io/gp_test/api/python/

As you can see it is still using `_static` to refer to those resources `.css`, `.js`, etc. https://github.com/maziyarpanahi/gp_test/blob/main/docs/api/python/index.html

**Comment by DevinTDHa** [comment]
@maziyarpanahi 
I checked my local version again, In that case, the files and references were correctly renamed to `"static"`.

```html
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Spark NLP Documentation &#8212; Spark NLP 3.1.3 documentation</title>

  <link href="static/css/theme.css" rel="stylesheet" />
  <link href="static/css/index.c5995385ac14fb8791e8eb36b4908be2.css" rel="stylesheet" />
...
```

I believe this might have something to do with how the `sed` shell command might be different between macOS and linux (https://stackoverflow.com/questions/4247068/sed-command-with-i-option-failing-on-mac-but-works-on-linux). 
I'll look into a cross platform solution.

**Comment by maziyarpanahi** [comment]
@DevinTDHa 
I think it's about the bash/env when the script is being executed. I am guessing it's not compatible with macOS. I'll see if I can make this part of GitHub actions automatically so it will be executed via linux environment

**Comment by DevinTDHa** [comment]
@maziyarpanahi 
That will probably work, if the github environment is based on linux.

I think adding the argument for backing up files as mentioned in the linked stackoverflow answer might work as well to make it compatible with all platforms

```bash
grep -RiIl '_static' _build | xargs sed -i .bak 's/_static/static/g'
```
I'll have to test it properly though.

**Comment by maziyarpanahi** [comment]
@DevinTDHa 
I am testing Github action job to build Scaladoc and PyDoc, if it works then we are good. It's even better not to bother with them during the release and let the GA takes care of them.

I'll let you know if it was a success while you are updating the rest.

**Comment by maziyarpanahi** [comment]
@DevinTDHa 
it was the `sed` command on macOS. I will make this command compatible with macOS for now. Many thanks

**Pull request merged**
