### PR TITLE
Corrected typo in the description

### PR DESCRIPTION
**Pull request by dcecchini**
The label `dosage` was used twice in "...It differs from `ner_posology` in the sense that it chunks together drugs, *dosage*, form, strength, *dosage*, and route when they appear together...". I changed the last one to `duration`.

## Description

Corrected a typo in the description of the model.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Code improvements with no or little impact
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Documentation improvement

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [CONTRIBUTING](http://nlp.johnsnowlabs.com/contribute.html) page.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by vkocaman — COMMENTED** [review]
Duration is not the part of this model.. additional `'dosage` will be dropped and all will be fine.

**Comment by dcecchini** [comment]
I see. Then I will also remove `duration` from the `Predicted Entities` part. I will make the changes now

**Comment by vkocaman** [comment]
@dcecchini why do you remove Duration ? it is one of the entities that this model predicts.. duration is not part of greedy mode but part the model itself

**Comment by dcecchini** [comment]
I removed because of your comment saying it is not part of the model. Please explain what you meant.

**Comment by dcecchini** [comment]
@HashamUlHaq can you please review how the description and predicted entities should be?

**Comment by HashamUlHaq** [comment]
@dcecchini here:

## Description

This model detects drugs, dosage, form, frequency, duration, route, and drug strength in text. It differs from `ner_posology` in the sense that it chunks together drugs, dosage, form, strength, and route when they appear together, resulting in a bigger chunk. It is trained using `embeddings_clinical` so please use the same embeddings in the pipeline.

## Predicted Entities

`DRUG`, `STRENGTH`, `DURATION`, `FREQUENCY`, `FORM`, `DOSAGE`, `ROUTE`.

you can just place it there.

**Comment by dcecchini** [comment]
@HashamUlHaq  and @vkocaman , I made the change as suggested by Hasham in [this commit](https://github.com/JohnSnowLabs/spark-nlp/commit/46420f875e8242cbe53a891b903e5be6e3dbd891).

Please let me know if it is correct.

**Comment by HashamUlHaq** [comment]
@dcecchini  looks fine now.

**Pull request merged**
