### PR TITLE
FEATURE NMH-94: Add model naming conventions [skip test]

### PR DESCRIPTION
**Pull request by pabla**
Add a toggle button for model naming conventions.

model_naming_conventions

### CODE REVIEW

**Comment by josejuanmartinez** [comment]
The only thing I'm thinking about right now, is - that information is very Healthcare related. Maybe we can have also other naming conventions from Open Source and OCR.

**Comment by maziyarpanahi** [comment]
@pabla Are the options in that box dynamic? (like if there is no BioBERT among the results, it won't show it right?)

**Comment by josejuanmartinez** [comment]
> @pabla Are the options in that box dynamic? (like if there is no BioBERT among the results, it won't show it right?)

I don't think they are. What I don't know is how difficult it is to do that. But would be nice. Because right now all we have is healthcare related.

**Comment by maziyarpanahi** [comment]
> > @pabla Are the options in that box dynamic? (like if there is no BioBERT among the results, it won't show it right?)
> 
> I don't think they are. What I don't know is how difficult it is to do that. But would be nice. Because right now all we have is healthcare related.

`large, `medium`, `small`, and `fast` can be public related. We have lots of models/pipelines with those names in their descriptions/names. But I hope we can update that list based on the results so we don't have to show a large list of names every time. (but we can have a place as `how to use Models Hub` to have all these info)

**Comment by josejuanmartinez** [comment]
thank you for the info about the open source models conventions. Let's have
it in the same models hub page, since this came from several clients
requests and Pavel has done already much work there. And in them meantime
for future updates we can think if we want them somewhere else.

**Review by maziyarpanahi — APPROVED** [review]

**Comment by pabla** [comment]
@maziyarpanahi No, the options aren't dynamic right now, but it is a good idea, let's implement that.

**Comment by pabla** [comment]
@maziyarpanahi @josejuanmartinez 
Maybe then is it worth to highlight naming conventions in the model titles and display them on hover instead of a button in the header?

Screenshot 2022-05-30 at 12 07 59 pxd copy@2x

**Comment by josejuanmartinez** [comment]
Yes, let's hover them, and also include the conventions that Maz commented
above

**Comment by pabla** [comment]
> Yes, let's hover them, and also include the conventions that Maz commented above.

@josejuanmartinez 
Could you please provide me descriptions for those conventions? (medium, small, fast)

**Comment by josejuanmartinez** [comment]
@maziyarpanahi can you provide a short desc for the open source conventions?
large, medium, small, and fast

**Comment by maziyarpanahi** [comment]
> @maziyarpanahi can you provide a short desc for the open source conventions? large, medium, small, and fast

sure:

large: used the largest size Word/Sentence Embeddings in this model/pipeline
medium: used the average size Word/Sentence Embeddings in this model/pipeline
small: used the smallest size Word/Sentence Embeddings in this model/pipeline
fast: used the fastest algorithms in this model/pipeline (speed over accuracy)

**Comment by pabla** [comment]
@josejuanmartinez @maziyarpanahi 
Here is an updated UI:
https://user-images.githubusercontent.com/1594817/171149292-442cc452-1e5e-4c4d-b796-d4c0c9a44202.mov

**Comment by josejuanmartinez** [comment]
@pabla  this looks great. I took a look to look for more naming conventions. Can you add the following?
- cased: This model differentiates between lowercase and uppercase.
- uncased: This model does not differentiate between lowercase and uppercase.
- normalized: in-house standardization and normalization of input and output labels

Also, I found some titles are not being fully shown, that will prevent to show the naming conventions in the title if they are at the end, right?
image

**Comment by pabla** [comment]
> Also, I found some titles are not being fully shown, that will prevent to show the naming conventions in the title if they are at the end, right?

Currently it works as you said. But after applying this PR, the title will be displayed fully (in the video above, the third card has a title with 5 lines).

**Review by josejuanmartinez — APPROVED** [review]

**Pull request merged**
